sa-token:
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 86400
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: 3600
  # jwt秘钥
  jwt-secret-key: template_secret_key_please_change_it_in_prod

  # 开启 Token 写入 Redis
  is-concurrent: false
  is-share: false
